### ISSUE TITLE
React Native Navigator

### ISSUE THREAD

**Issue by montogeek** [FaridSafi/react-native-gifted-form#1]
Hi!

Is this component compatible with the default RN Navigator component?

Thanks!

**Comment by FaridSafi** [comment]
Hello @montogeek,
I didn't test but I think it's possible to make it compatible using the openModal prop.
Here some indications:

```js
        // default example
        openModal={(route) => {
          navigator.push(route); // The ModalWidget will be opened using this method. Tested with ExNavigator
        }}
```

The object route is defined here
https://github.com/FaridSafi/react-native-gifted-form/blob/master/widgets/ModalWidget.js#L72
As you can see it defines renderScene, getTitle, configureScene, renderLeftButton, renderRightButton

If you are using the default navigator I guess you need to pass this route object directly to your Navigator renderScene and to use it

**Comment by m4rcoperuano** [comment]
@montogeek It can work with Navigator, but it does require some extra work (not much though). I updated the openModal={..} function to this:

```jsx
openModal={ (route) => {
             route.giftedForm = true;
             this.props.navigator.push(route); 
         }}>
```

I set the giftedForm property so that in my navigator methods, I can do some conditional statements. Here is my navigator in my root page render method:
```jsx
<Navigator
       ref="navigator"
       initialRoute={Routes.getInitialRoute()}
       renderScene={this.renderScene}
       configureScene={this.configureScene}
       navigationBar={this.setNavigationBar()}
/>
```

The renderScene and configureScene function looks something like this:
```jsx
renderScene: function (route, navigator) {
//...
     if (route.giftedForm == true) {
          return route.renderScene();
     }
//...
},

configureScene: function (route) {
        //...
        if (route.giftedForm) {
            return route.configureScene();
        }
       //...
    },
}
```

The Route object provided by Gifted Form has all the necessary methods you need to create your title, left bar button, right bar button, and scene configuration. 

The only issue I have is that the modal icons are images, and I can't change the color without going into the package :(. Maybe sometime you can integrate react-native-vector-icons? 

Anywho, thanks @FaridSafi for the awesome tool!

**Comment by m4rcoperuano** [comment]
Just adding to the "only issue" i had - the icons can be set a tint color, but it looks like the tint color isn't exposed in the API. Or is it? Maybe i missed something in the documentation?

**Comment by akshaysinghi** [comment]
I am getting this error when am using
<GiftedForm  formName='signupForm' 
        openModal={ (route) => {
             route.giftedForm = true;
             this.props.navigator.push(route);  }}>

ERROR is : undefined is not an object (evaluating '_this2.props.navigator.push') during openModal .
Any help ?

**Comment by m4rcoperuano** [comment]
Try consoling logging "this.props" to make sure you have "navigator" as a property. If not, it needs to get passed into your component, i.e: <MyComponent navigator={this.myNavigatorInstance} />

**Comment by yukunwu** [comment]
@FaridSafi 
Hi, would you make an compact with RN navigator?It is good not to bind it to an coustom navigator(@exponentjs/ex-navigator).Follw steps as @m4rcoperuano described,when open modal in android,we should manuly add ToolbarAndroid to it.
Would you make it better.
Thanks.

**Comment by girish989** [comment]
@montogeek @FaridSafi @m4rcoperuano -

I am trying to get this working and I am not getting the tool bar. 

I am using react native navigator 👍 

In app.js my configureScene method:

`configureScene(route) {
    if (route.giftedForm == true) {
          return route.configureScene();
     }
  }`


My renderScene method:

`renderScene(route, navigator) {
    if (route.giftedForm == true) {
          return route.renderScene();
     }
}`

After - that my openmodal method is - 

` openModal={(route) => {
                   console.log('route::',route);
                   route.giftedForm = true;
                   this.props.navigator.push(route); 
                 }}`


is there anything else I need to to make the toolbar appear ?

Thank you very much in advance for the help.

**Comment by weixingsun** [comment]
Bar is just another <View>...</View> 
do anything you want in widgets/ModalWidget -> renderScene()
Don't wait for reply from @FaridSafi , everybody has limited time.
anyway, this module is good enough, oh no, it's fantastic

**Comment by csmtcy** [comment]
@girish989 i'm using the nativebase.io, simply put in the header will get the toolbar appear
```javascript
<GiftedForm.ModalWidget
               title='Gender'
               displayValue='gender'
               image={require('./../../img/icons/apartment.png')}
               scrollEnabled={false}
             >
               <Container style={styles.container}>
                 <Header style={styles.header}>
                   <Button transparent onPress={()=>{this.props.navigator.pop()}}>
                     <Icon name="ios-arrow-back" size={30} style={{color: theme.textColor}} />
                   </Button>
                   <Title style={{color: theme.textColor, fontFamily: theme.fontFamily}}>Gender</Title>
                 </Header>
                 <Content style={styles.content}>
                   <GiftedForm.SelectWidget name='gender' title='Gender' multiple={false}>
                     <GiftedForm.OptionWidget image={require('./../../img/icons/apartment.png')} title='Female' value='F'/>
                     <GiftedForm.OptionWidget image={require('./../../img/icons/apartment.png')} title='Male' value='M'/>
                   </GiftedForm.SelectWidget>
                 </Content>
               </Container>
             </GiftedForm.ModalWidget>
```

**Comment by elie222** [comment]
anyone had success with this package an `ex-navigation`?

**Comment by nickkapoor** [comment]
@montogeek was wondering how to set the navigator object up.  As per your recommendation, I do not know what Routes.getInitialRoute() would translate into?  I have a navigatorRenderScene function in my main app.  which switches based upon route.id.  I set the route.id as follows:

 return (
            <GiftedForm
                formName='signupForm'
                openModal={(route) => { 
                route.giftedForm = true;
                route.id = 'RegisterUser';
                this.props.navigator.push(route) ;
                }}
                onValueChange={this.handleValueChange.bind(this)}
            >

and in my main app I set the   
navigatorRenderScene(route, navigator) {
        _navigator = navigator;
        switch (route.id) {
  case 'RegisterUser':  //modal page
                return (<Navigator
                    ref="navigator"
                    initialRoute={Routes.getInitialRoute()}
                    renderScene={this.renderScene}
                    configureScene={this.configureScene}

                />)
I have added the configure and render Scene methods.  For the time being I took out the toolbar property.  Am wondering if you can assist here.  

Question: What will be the Routes.getInitialRoute()?  How can I get a reference to Routes?  
Thanks

 ......
configureScene(route) { if (route.giftedForm == true) { return route.configureScene(); } }

renderScene(route, navigator) { if (route.giftedForm == true) { return route.renderScene(); } }


....
<Navigator
       ref="navigator"
       initialRoute={Routes.getInitialRoute()}
       renderScene={this.renderScene}
       configureScene={this.configureScene}
       navigationBar={this.setNavigationBar()}
/>
