### ISSUE TITLE
styling placeholder text...

### ISSUE THREAD

**Issue by cmdillon** [FaridSafi/react-native-gifted-form#12]
hi! i was wondering if it's possible to style the 'placeholder' text. would like to change it's color.

**Comment by FaridSafi** [comment]
Hello, I guess placeholderTextColor prop in TextInputWidget should work

**Comment by cmdillon** [comment]
tried this:
`placeholderTextColor: {
                  color: '#fff'
                }`
but didn't work. any ideas?

**Comment by FaridSafi** [comment]
https://facebook.github.io/react-native/docs/textinput.html

Should be a string not an object

**Comment by cmdillon** [comment]
cool! that worked for me—thanx

**Comment by dajimene** [comment]
Hello friends somebody help me by indicating how to change the TextInputWidget properties of react-native-gifted-form.
I need to change the colors of the lines that are by default at the time of starting the screen and to recover the focus in the text box.
What I can see there are colors by default but I can not find where to change.
The CSS properties that are in TextInputWidget.js do not change the design
Thank you

**Comment by dajimene** [comment]
Hello friends somebody help me by indicating how to change the TextInputWidget properties of react-native-gifted-form.
I need to change the colors of the lines that are by default at the time of starting the screen and to recover the focus in the text box.
What I can see there are colors by default but I can not find where to change.
The CSS properties that are in TextInputWidget.js do not change the design
Thank you

![image](https://cloud.githubusercontent.com/assets/27232120/26524535/4776e210-42fb-11e7-9e71-36cf6e6c9319.png)

**Comment by dajimene** [comment]
Hello friends somebody help me by indicating how to change the TextInputWidget properties of react-native-gifted-form.
I need to change the colors of the lines that are by default at the time of starting the screen and to recover the focus in the text box.
What I can see there are colors by default but I can not find where to change.
The CSS properties that are in TextInputWidget.js do not change the design
Thank you

![image](https://cloud.githubusercontent.com/assets/27232120/26524559/6ca288c2-42fc-11e7-9335-eaa820c3abe5.png)
