### ISSUE TITLE
changing color of clearButtonMode image

### ISSUE THREAD

**Issue by cmdillon** [FaridSafi/react-native-gifted-form#13]
hi! i was wondering if there is a way to change the color of 'clearButtonMode'  image that appears on the right side of the text view.

**Comment by FaridSafi** [comment]
Hello, it depends of the react-native TextInput core component. As I know it's not possible

**Comment by cmdillon** [comment]
i found this threads maybe can help:
[http://stackoverflow.com/questions/27944781/how-to-change-the-tint-color-of-the-clear-button-on-a-uitextfield](url)

**Comment by lixutao** [comment]
could you tell me how to replace it? thank you!
