### ISSUE TITLE
Providing Title But Don't Display It

### ISSUE THREAD

**Issue by graywolf336** [FaridSafi/react-native-gifted-form#25]
Looking through the code an examples, seems the only way to hide the title is to not provide it. I would like to provide titles but not have them displayed, as my form style uses placeholders for the titles yet the validation messages rely on the title for the name of the field.

After looking through the code, seems like an easy addition and when I get home I'll see about submitting a pull request.

**Comment by FaridSafi** [comment]
Hello @graywolf336 
Regarding validation messages, are you talking about 
```js
              message: '{TITLE} can contains only alphanumeric characters'
```
?

If yes, you can replace {TITLE}  by the title you want

**Comment by graywolf336** [comment]
@FaridSafi Yes and no. That's one of the places the title is referred to but the messages in #26 also use the title. But we are building a class which contains a lot of validators and using them on different form components, so the title is required as they are on other field names with different titles. I'll be submitting a pull request for the text input as that's the only one I'm using right now, unless there's a list of widgets which display the title in the list of them.

The prop I'm considering using is `displayTitle` and it's just a boolean which defaults to `true`. Thoughts?

**Comment by FaridSafi** [comment]
Sorry but I don't understand why not passing the Title to the widget is an issue.
Where the missing title is displayed?
Title of the Widget is a different value than the Title from the validators prop

**Comment by graywolf336** [comment]
That makes sense now, thanks for clarifying.
