### ISSUE TITLE
Example code incorrect

### ISSUE THREAD

**Issue by GrumpyPants** [FaridSafi/react-native-gifted-form#3]
Two minor things/questions. 
1. Is this [var](https://github.com/FaridSafi/react-native-gifted-form/blob/master/GiftedFormManager.js#L152) meant to be global or is this a typo?
2. For the example code:
```
clearOnClose: false, // delete the values of the form when unmounted
```
 there should not be a comma here correct? This causes an Unidentified character exception.

Also, the example code doesn't seem to work for me at all. I just get an error "Namespace attributes are not supported. ReactJSX is not XML". It may be good to add an example dir with an xcode project that you could run similar to what they did with the react native [UI explorer](https://github.com/facebook/react-native/tree/master/Examples/UIExplorer)

**Comment by FaridSafi** [comment]
Hello @GrumpyPants,
1. This var is meant to be an attribute of the FormManager. Current fields values and validators are stored in it
2. You right, it's not correct syntax

I just added an Example but I can't make ex-navigator working with react-native 0.18.1 yet
