### ISSUE TITLE
Cancel (Back) from Modal.

### ISSUE THREAD

**Issue by joshuapinter** [FaridSafi/react-native-gifted-form#32]
I have a date modal just like the docs, like this: 

``` js
<GiftedForm.ModalWidget
  title='Last Activity'
  displayValue='lastActivity'
  scrollEnabled={false} 
>

  <GiftedForm.SeparatorWidget/>
  <GiftedForm.DatePickerIOSWidget
    name='lastActivity'
    mode='date'

    getDefaultDate={() => {
      return moment().toDate();
    }}
  />
</GiftedForm.ModalWidget>
```

This modal shows up with just a check box, like this: 

![screenshot 2016-02-26 10 02 21](https://cloud.githubusercontent.com/assets/180819/13359174/0a5da7a8-dc70-11e5-890f-17ff6954a969.png)

But is there any way to go back from this and cancel any input, like a back or cancel button in the top left of the navbar?

Thanks!

**Comment by FaridSafi** [comment]
Hello, I am afraid that it's not supported.
There is the ```cancelable``` bool prop in the ModalWidget, but when you use it it closes the Modal and still keep the current widget value in form states.
You can make some modifications to the onClose method of ModalWidget to allow you to set the widgets values (a modal can contains multiple widgets) to the previous state (so you need to store the initial state then to re apply it) when you close the modal. 

If you can make it, a pull request will be much appreciated

**Comment by joshuapinter** [comment]
Thanks for the response Farid. I'll take a look at making the change once I get this first version out the door.
