### ISSUE TITLE
How to set selected value of SelectWidget.

### ISSUE THREAD

**Issue by joshuapinter** [FaridSafi/react-native-gifted-form#33]
I see that you can set the default value of a `SelectWidget` by using: 

``` js
defaults={{
  'frequency{4}': true
}}
```

But I'm passing an object in to edit it using the form so the value is dynamic based on that object. So how would I go about setting the selected value in the SelectWidget and not through the `defaults`.

Something like this: 

``` js
<GiftedForm.SelectWidget name='frequency' title='Frequency' multiple={false} value='4'>
  <GiftedForm.OptionWidget title='Weekly'      value='1'/>
  <GiftedForm.OptionWidget title='Monthly'     value='4'/>
  <GiftedForm.OptionWidget title='Quarterly'   value='12'/>
</GiftedForm.SelectWidget>
```

Thanks!

**Comment by FaridSafi** [comment]
Sorry but I don't understand why you don't want to use ```defaults``` prop. It is because the frequency value can change after that the form is mounted ?

At the moment, there is no other way to set the SelectWidget default value

**Comment by joshuapinter** [comment]
Thanks for the reply Farid!
After a bit more experimentation, the defaults should work just fine. However, I
was having trouble using a variable for the value in the format:
'''js "Gender{M}": true '''
How would I use 'this.props.myrecord.gender' in place of "M"?

**Comment by FaridSafi** [comment]
You can do something like
```js
var key = 'gender{'+this.props.myrecord.gender+'}';
var myDefaults = {};
myDefaults[key] = true;
<GiftedForm defaults={myDefaults} />
```

**Comment by luoxiaolei** [comment]
hello，
```
<GiftedForm.SelectWidget`` name='gender' title='Gender' multiple={false} defaults={{'gender{F}': true}}>
                                    <GiftedForm.OptionWidget title='男' value='F'/>
                                    <GiftedForm.OptionWidget title='女' value='M'/>
                                </GiftedForm.SelectWidget>
```
I want to set default value,but does not work,could you give me a demo?thanks!

**Comment by gauravverma029** [comment]
How to set Multiple values in SelectWidget when multiple is true.
