### ISSUE TITLE
Submit Form from Navbar Button? 

### ISSUE THREAD

**Issue by joshuapinter** [FaridSafi/react-native-gifted-form#34]
Hi Guys. 

I've got a "Save" button in the top right of my navbar that I would like to use to submit my Gifted Form (basically the `onSubmit` stuff in `GiftedForm.SubmitWidget`). 

I looked through the GiftedFormManager to see if there was an external method to call but don't see any. 

Any ideas? 

Many Thanks!

Josh

**Comment by FaridSafi** [comment]
Hello @joshuapinter, you can use the GiftedFormManager to validate and to get the form values
```js
GiftedFormManager.validate('formName'); // will return you an object with the validations tests
GiftedFormManager.getValues('formName'); // will return you the values of the widgets
```
To make your Submit button enabled only if all widgets are valid you can take a look at the onValidation prop. See https://github.com/FaridSafi/react-native-gifted-form/pull/17

**Comment by joshuapinter** [comment]
Okay, perfect. I'll just wrap the onSubmit stuff into a method that can be called from either the submit button or a navbar button. 

Thanks.
