### ISSUE TITLE
Android 

### ISSUE THREAD

**Issue by johntom** [FaridSafi/react-native-gifted-form#45]
Hi,
Just tested your example on android.
1) missing moment in app.js
fix import moment from 'moment';
2) missing theme
fix replace theme with color
<GiftedForm.SubmitWidget
              title='Sign up'
              widgetStyles={{
                submitButton: {
                  backgroundColor:'cadetblue ',
                  // or  'transparent' or see                   //https://facebook.github.io/react-native/docs/colors.html
                  // themes.mainColor,
                }
              }}
3) Search on country
It works but raises a warning: each child in an array or iterator should have a unique :key" prop. Check the render method of 'ListView'. sell https://fb.me/react-warning-keys
Thanks,
John

**Comment by cooperka** [comment]
Should be resolved now by https://github.com/FaridSafi/react-native-gifted-form/pull/84.
