### ISSUE TITLE
formStyles for ValidationErrorWidget are broken

### ISSUE THREAD

**Issue by carlinisaacson** [FaridSafi/react-native-gifted-form#49]
When I try to set the styles via `formStyles` in my GiftedForm component the styles don't change. I did some debugging and when the `getStyles` function is called from the `ValidationErrorWidget` [this line](https://github.com/FaridSafi/react-native-gifted-form/blob/fd515d625babad8f22d47d8528506d514009325b/mixins/WidgetMixin.js#L94) in the WidgetMixin returns undefined for `typeof this.props.formStyles[this.props.type][styleNames[i]]`. 

Also tried changing styles in the example app and there is no change there either.

**Comment by gabceb** [comment]
The snippet below is working for me to style validationErrorWidgets per widget type

```js
formStyles={{
  TextInputWidget: {
    rowContainer: Styles.textInputRow,
    textInputInline: Styles.textInput,
    validationError: {
      color: 'green'
    },
    validationErrorRow: {
      backgroundColor: 'yellow'
    }
  },
}}
```

**Comment by carlinisaacson** [comment]
That is working for me. I was setting it up the way Farid showed in issue #21. I implemented styles like this:

```
  formStyles={{
    TextInputWidget: {
      rowContainer: Styles.textInputRow,
      textInputInline: Styles.textInput
    },
    ValidationErrorWidget: {
      validationErrorRow: {
        backgroundColor: 'yellow'
      },
      validationError: {
        color: 'green',
      }
    }
  }}
```

It looks like, because the `ValidationErrorWidget` is rendered in from within the `TextInputWidget`, the error styles have to go in the text input styles.

Thanks @gabceb. Closing.
