### ISSUE TITLE
reset and resetValue in GiftedFormManager both call handleReset

### ISSUE THREAD

**Issue by ScandyMark** [FaridSafi/react-native-gifted-form#5]
reset and resetValue in GiftedFormManager both call handleReset.  But there is a handleResetValues which looks like it would be more logical to call from resetValue.  Not familiar enough with code to actually call this an error, but it seems odd.

**Comment by FaridSafi** [comment]
You are right @ScandyMark. resetValues should call handleResetValues instead of handleReset

**Comment by FaridSafi** [comment]
Thanks, I fixed this in 0.0.2
