### ISSUE TITLE
RN 26 import changes

### ISSUE THREAD

**Issue by carlinisaacson** [FaridSafi/react-native-gifted-form#59]
I am using gifted form in my project and we just updated our imports to match the new standard coming in RN 26. In doing so we found that this package has not been released with the new standard yet. I fixed this by pointing my package.json to the github repo. 

I then found that one of this package's dependencies (react-native-google-places-autocomplete) has the same issue. To fix it I had to fork this repo and point the dependency to the react-native-google-places-autocomplete github repo.

Please push new releases of both this package and the react-native-google-places-autocomplete package that include the new import standards so gifted form can be pulled from npm and be up to date with RN 26 standards.

**Comment by FaridSafi** [comment]
Thank you @carlinisaacson. Sorry for late reply.
Fixed in 0.0.8

**Comment by derekgreenberg** [comment]
@FaridSafi Thank you for your prompt merge of this PR!

**Comment by carlinisaacson** [comment]
@FaridSafi Thank you!
