### ISSUE TITLE
set multiple SelectWidget default value does not work

### ISSUE THREAD

**Issue by luoxiaolei** [FaridSafi/react-native-gifted-form#64]
`var key = '\'gender{' + profile.gender + '}\'';
        var genderDefault = {};
        genderDefault[key] = true;
        console.log(genderDefault);
        key = '\'zhuanye{' + profile.zyId.name + '}\'';
        var zhuanyeDefault = {};
        zhuanyeDefault[key] = true;
        console.log(zhuanyeDefault);
        key = '\'title{' + profile.titleId.name + '}\'';
        var titleDefault = {};
        titleDefault[key] = true;
        console.log(titleDefault);
        key = '\'zgzh{' + profile.zgzId.name + '}\'';
        var zgzhDefault = {};
        zgzhDefault[key] = true;
        console.log(zgzhDefault);
        key = '\'specialty{' + profile.zkId.name + '}\'';
        var specialtyDefault = {};
        specialtyDefault[key] = true;
        console.log(specialtyDefault);`
`defaults={{genderDefault,zhuanyeDefault,titleDefault,zgzhDefault,specialtyDefault}}`

why?

**Comment by sambwest** [comment]
You have it nested to deep. defaults should equal {fieldKey: fieldValue, fieldKey: fieldValue}, you have {{fieldKey: fieldValue}, {fieldKey: fieldValue}}. 

Using  your first example:

`defaults={{genderDefault}}`

Would equate to:

`defaults={{{key: true}}`

When it should be:

`defaults={{key: true}}`

(p.s. try formatting your code next time!)

**Comment by luoxiaolei** [comment]
thank you very much!
