### ISSUE TITLE
this library (validator.js) validates strings only

### ISSUE THREAD

**Issue by bionimic** [FaridSafi/react-native-gifted-form#75]
how can i solve this? im using RN 32

**Comment by sambwest** [comment]
I had that issue but was able to solve it by adding defaults to the GiftedForm.

Hope this helps.

**Comment by bionimic** [comment]
Can you give me example? Which default config are you refering to? Is the default value?

**Comment by sambwest** [comment]
Yes, a default value...

```
<GiftedForm
          defaults={{
            duration: '1',
            atendee: 'Me'
          }}
```

**Comment by bionimic** [comment]
Noted. Thanks!

**Comment by frmdstryr** [comment]
This doesn't seem to work for the DatePickerIOSWidget, anyone else seeing this?

**Comment by cooperka** [comment]
Hmm, this is still something we should solve, even if there is a workaround (thank you @sambwest). @frmdstryr would you be willing to submit a PR to fix it?

**Comment by cooperka** [comment]
Closing as there is a duplicate issue with better details: https://github.com/FaridSafi/react-native-gifted-form/issues/90
