### ISSUE TITLE
Without "defaults" form crashes on submit

### ISSUE THREAD

**Issue by jagi** [FaridSafi/react-native-gifted-form#90]
When I try to submit form without defaults and with empty fields I get the `This library (validator.js) validates strings only` error. I assume that this bug is caused by form values being `undefined` on form init. So after not focusing or changing form input it will try to validate `undefined` values. Solution could be copying all inputs' values at form init.

![simulator screen shot 18 nov 2016 16 11 51](https://cloud.githubusercontent.com/assets/1051229/20434777/bd285b8e-ada9-11e6-8905-4abc8a21303d.png)

**Comment by KayAlbertus** [comment]
Any Solution to the above ?

**Comment by ktroach** [comment]
Needs to have a null check on strings prior to asserting the length of the string.

**Comment by arberK** [comment]
+1

**Comment by cooperka** [comment]
This is a verified issue, thank you! A PR would be welcome if anyone wants to tackle this.

**Comment by frmdstryr** [comment]
https://github.com/frmdstryr/react-native-gifted-form/commit/68c1b5ebbdc1efae5116d298ddcb6783d35578c8

Fixes the validation errors.  I'm still having issues with the date being reflected properly when selected (not sure if this is another issue or related at the moment).

**Comment by cooperka** [comment]
@frmdstryr I've fixed it and released v0.0.15, please try again :) The date seems to be working for me.

**Comment by frmdstryr** [comment]
Yep, working good now. Thanks!
