### ISSUE TITLE
Getting Warning: 'keyboardShouldPersistTaps={true} is deprecated.'

### ISSUE THREAD

**Issue by bityogi** [FaridSafi/react-native-gifted-form#94]
I am playing round with GiftedForm and so far like this library a lot.

However, I get a warning message on the simulator stating that:

`'keyboardShouldPersistTaps={true}' is deprecated. Use 'keyboardShouldPersistTAps="always" instead.`

I am using:

```
"react-native": "0.40.0",
"react-native-gifted-form": "0.0.13",
```
Is there somewhere that I can override this property?

**Comment by jagi** [comment]
I have the same problem

**Comment by moxun33** [comment]
'keyboardShouldPersistTaps={true}' is deprecated. Use 'keyboardShouldPersistTaps="always"' instead

How to fix it?

**Comment by garmjs** [comment]
I'm getting this too

**Comment by tungpt92** [comment]
it fixed in RN 0.39.2

**Comment by kaiyes** [comment]
I have the same issue. but the infamous @jagi is here. Meteor's famous schema package writer :D

**Comment by BruceHem** [comment]
I'm using "react-native": "0.41.2" getting this message also? how can i fix this?

**Comment by tungpt92** [comment]
change your RN version to 0.39.2 in package.json file, then remove your node_modules folder in that RN project, open Nodejs command promt cd projectname -> npm install
It will be fixed

**Comment by cooperka** [comment]
Should be fixed by https://github.com/FaridSafi/react-native-gifted-form/pull/95.

**Comment by acomito** [comment]
I'm getting this warning using Expo's latest version (16.0)
